export const SET_SEARCH_LIST = "SET_SEARCH_LIST";
export const SET_TOTAL_PAGE = "SET_TOTAL_PAGE";
export const SET_PAGE_NUM = "SET_PAGE_NUM";
export const SET_SEARCH_NOT_FOUND = "SET_SEARCH_NOT_FOUND";
export const SET_SEARCH_NOT_FOUND_MESSAGE = "SET_SEARCH_NOT_FOUND_MESSAGE";